name: CI/CD Docker Image Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Get Current Version
        id: version
        run: |
          VERSION=$(git describe --tags --match "v*" --abbrev=0 || echo "v0.0.0")
          echo "CURRENT_VERSION=${VERSION#v}" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$VERSION"


      - name: Calculate New Version
        id: new_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            NEW_VERSION="${{ github.ref#refs/tags/ }}"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<<"${{ env.CURRENT_VERSION }}"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version is $NEW_VERSION"


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-fusion-webapi:v${{ env.NEW_VERSION }}
          context: ./devops.fusion.webapi
          file: ./devops.fusion.webapi/Dockerfile
